### ISSUE TITLE
The question about ambient noise simulation

### ISSUE THREAD

**Issue by xichaoqiang** [ziyixi/pyfk#1] opened 2020-12-16 01:52 UTC
Dear Xi

Thanks for sharing the pyfk package.I am intrested in ambient noise disperison imaging.

Can this package do some ambient noise simulation like the Section 3 in the attachemt file?

![图片](https://user-images.githubusercontent.com/30900789/102294511-6e147700-3f84-11eb-85a6-d982bbbee6e4.png)

[2018JB016595.pdf](https://github.com/ziyixi/pyfk/files/5699799/2018JB016595.pdf)

Best regards,
Xi

**Comment by ziyixi** [comment] 2020-12-16 02:41
Hello,

This package is designed to calculate the waveform from the 1D Earth model. I heard there are two different types of "FK". One is the FK package developed by Prof. Lupei Zhu that is widely used to calculate the waveform, another is the FK  analysis, which might be your case. I don't have experience in dispersion imaging, and I am even afraid if this package can accurately simulate the surface wave. Since this package is simply a duplicate of the FK package, it should have the same usage as the FK.

**Comment by xichaoqiang** [comment] 2020-12-16 02:49
Dear Xi

Thanks for your reply.I want get some synthetic waveforms with the 1D Earth model for dispersion image.

The synthetic waveform of ambient noise like the summation of waveform with differernt source-receiver parameters.

If the package can accurately simulate the Rayleigh or Love wave,I think it can simulate the ambient noise.

Best regards,
Xi

**Comment by ziyixi** [comment] 2020-12-16 03:05
To my knowledge, it seems there is no reason why FK can't simulate the surface wave. But I have never tried that, and mostly calculate the body wave. Maybe you can have a test? 

And according to this issue https://github.com/dmelgarm/MudPy/issues/11#issuecomment-244985831 , they are saying FK might be able to calculate the surface wave. But I really have no idea about that.

**Comment by xichaoqiang** [comment] 2020-12-16 03:07
Thanks for your reply. I will try it. Good Job.

**Closed** 2020-12-18 05:02 UTC
